# Site settings
title: Ochsenkofler
email: info@ochsenkofler.it
description: Ochsenkofler...
baseurl: "/ochsenkofler.it/" # the subpath of your site, e.g. /blog/
url: "http://toburger.github.io/" # the base hostname & protocol for your site
twitter_username: toburger
github_username:  toburger

# Build settings
markdown: kramdown
